/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BackofficeRouteImport } from './routes/_backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeManagementIndexRouteImport } from './routes/_backoffice/management/index'
import { Route as BackofficeManagementUsersIndexRouteImport } from './routes/_backoffice/management/users/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/_backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeManagementIndexRoute =
  BackofficeManagementIndexRouteImport.update({
    id: '/management/',
    path: '/management/',
    getParentRoute: () => BackofficeRoute,
  } as any)
const BackofficeManagementUsersIndexRoute =
  BackofficeManagementUsersIndexRouteImport.update({
    id: '/management/users/',
    path: '/management/users/',
    getParentRoute: () => BackofficeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recommend': typeof RecommendRoute
  '/test': typeof TestRoute
  '/management/': typeof BackofficeManagementIndexRoute
  '/management/users/': typeof BackofficeManagementUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recommend': typeof RecommendRoute
  '/test': typeof TestRoute
  '/management': typeof BackofficeManagementIndexRoute
  '/management/users': typeof BackofficeManagementUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_backoffice': typeof BackofficeRouteWithChildren
  '/about': typeof AboutRoute
  '/recommend': typeof RecommendRoute
  '/test': typeof TestRoute
  '/_backoffice/management/': typeof BackofficeManagementIndexRoute
  '/_backoffice/management/users/': typeof BackofficeManagementUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/recommend'
    | '/test'
    | '/management/'
    | '/management/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/recommend'
    | '/test'
    | '/management'
    | '/management/users'
  id:
    | '__root__'
    | '/'
    | '/_backoffice'
    | '/about'
    | '/recommend'
    | '/test'
    | '/_backoffice/management/'
    | '/_backoffice/management/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  AboutRoute: typeof AboutRoute
  RecommendRoute: typeof RecommendRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backoffice': {
      id: '/_backoffice'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backoffice/management/': {
      id: '/_backoffice/management/'
      path: '/management'
      fullPath: '/management/'
      preLoaderRoute: typeof BackofficeManagementIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/management/users/': {
      id: '/_backoffice/management/users/'
      path: '/management/users'
      fullPath: '/management/users/'
      preLoaderRoute: typeof BackofficeManagementUsersIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeManagementIndexRoute: typeof BackofficeManagementIndexRoute
  BackofficeManagementUsersIndexRoute: typeof BackofficeManagementUsersIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeManagementIndexRoute: BackofficeManagementIndexRoute,
  BackofficeManagementUsersIndexRoute: BackofficeManagementUsersIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  AboutRoute: AboutRoute,
  RecommendRoute: RecommendRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
